name: Actualizar reseñas
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run script
        run: node scripts/fetch_reviews.js
        env:
        GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}

      - name: Commit changes
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git add reviews.json
    git commit -m "Actualizar reseñas" || echo "No changes"
    git pull --rebase
    git push